### ISSUE TITLE
Can't use AUTH_TYPE.AMAZON_COGNITO_USER_POOLS in config - window is not defined

### ISSUE THREAD

**Issue by lolcoolkat** [dabit3/next-apollo-appsync#1]
I know there was this issue awhile back.. but I can't use the following in my config..

```
import { Auth } from 'aws-amplify'
import { AUTH_TYPE } from 'aws-appsync/lib/link/auth-link'

export default {
  url: 'https://xxxxxxxxxxxxxxxxxxxxxxxxx-api.us-east-1.amazonaws.com/graphql',
  region: 'us-east-1',
  auth: {
    // Amazon Cognito user pools using AWS Amplify
    type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
    jwtToken: async () =>
      (await Auth.currentSession()).getIdToken().getJwtToken(),
  },
}
```

It gives the following error: **UnhandledPromiseRejectionWarning: ReferenceError: window is not defined**

![Error](https://i.imgur.com/6Y8Knmg.png)

Look's like the error has been addressed here: https://github.com/aws/aws-amplify/issues/882 Is there nothing we can do until this bug is fixed?

**Comment by lolcoolkat** [comment]
Did a little research and it look's like some updates to aws-amplify haven't been pushed yet to a new version. 

Did ``` yarn upgrade aws-amplify@0.4.2-unstable.21``` and it seemed to fix the window error.

**Comment by dabit3** [comment]
@lolcoolkat ver interesting, thanks for pointing this out. I'll check into this and see what we can do :)

**Comment by lolcoolkat** [comment]
Btw @dabit3 doing the following doesn't work on the server with SSR...
```
Auth.currentSession()).getIdToken().getJwtToken()
```

So instead of using that function.. I figured i'll just get the accessToken I need manually and pass that directly to  the AWSAppSyncClient..

First thing that needs to change is in the AWS Amplify config adding the cookieStorage settings like so:
```
cookieStorage: {
   domain: 'localhost', //or whatever domain
   path: '/',
   expires: 365,
    secure: false,
 }
```

We need to extract the accessToken from the cookies..and pass that to the AppSync client. I'm using the following function to extract it out..
```
export function getValueFromKey(req, string) {
  const cookies = parseCookies(req)
  const key = Object.keys(cookies).filter(k => k.includes(string))
  return key.length ? cookies[key] : ''
}
```
and calling it like so: 
```
 const apollo = initApollo(
        {},
        {
          ...config,
          getToken: () => getValueFromKey(req, 'accessToken'),
        },
      )
```

This solution seems to be working... but hopefully a solution by aws amplify for supporting SSR would be nice in the future.

I made an issue thread here awhile back before I explored this solution: https://github.com/aws/aws-amplify/issues/951

**Comment by dabit3** [comment]
Ok @lolcoolkat I just checked on this and it seems to be an issue with the current implementation of AWS Amplify. This issue is already being tracked as a future enhancement and will be fixed in Amplify in the near future.

I'll leave this open to others looking to use this and possibly use your workaround, and will update as soon as it's fixed in the main AWS Amplify SDK.

Thanks for pointing this out!

**Comment by jsierles** [comment]
Did this get fixed?

**Comment by masato-io** [comment]
wondering if this is fixed as well.

**Comment by Enalmada** [comment]
@dabit3 Is there a place where we can see tracking on this in Amplify?

**Comment by sakhmedbayev** [comment]
@dabit3 any news on this front? Please let us know!

**Comment by sakhmedbayev** [comment]
> We need to extract the accessToken from the cookies..and pass that to the AppSync client. I'm using the following function to extract it out..

@lolcoolkat thanks for sharing your solution. Can you please tell how you placed `accessToken` to the `cookieStorage`?

**Comment by sakhmedbayev** [comment]
@lolcoolkat do you also tweaking `server.js` file to make your solution work? Something like showing here https://github.com/aws-amplify/amplify-js/issues/493#issuecomment-451272638 ?

**Comment by dabit3** [comment]
To the best of my knowledge this is on the roadmap but there is no specific date yet set for it. For better visibility, consider posting the same issue in the Amplify JS repo, from there the team should be able to give more info than I have.

https://github.com/aws-amplify/amplify-js/issues

**Comment by ajhool** [comment]
These are some related issues in amplify-js

https://github.com/aws-amplify/amplify-js/issues/3201 

https://github.com/aws-amplify/amplify-js/issues/2054 

https://github.com/aws-amplify/amplify-js/issues/3015 

I consider the lack of support for SSR in Amplify to be a terrible oversight. Particularly because SSR works for most of the components, so it lures you into a false sense of security -- but if Auth doesn't work properly, then the entire framework is useless. The worst part is that the error is silent, so I don't even know where to begin debugging the issue or offering a patch. If this is an issue for you, please be vocal on the amplify github issues section because they are responsive to feedback.
